### ISSUE TITLE
Application Organization Request

### ISSUE THREAD

**Issue by lemonleim** [Next-Flip/Momentum-Apps#12]
I am very happy to have found this repo! I am relatively new to F0 and GitHub, but I am curious if (maybe I just don't know how to do it myself but if) there's a way to organize these applications into folders by category (see attached for categories). I had downloaded UberGuidoz repo a few months ago when I was trying to use Xtreme and it was very easy to import apps to the already-made folders on the SD card. It'd be great if I could just copy a folder (or all the contents of a folder) to my Flipper and keep them organized by category.

Thanks for all the work y'all are doing!

![Screenshot 2024-08-02 185648](https://github.com/user-attachments/assets/1edd2346-351f-4550-a81f-42823a6b34c7)

**Comment by WillyJL** [comment]
The apps in this repo are organized in the same way. Issue is, you're looking at source code. After compiling, they are organized. This repo is not meant to be installed as is. Go install momentum, all the apps here are included with momentum, and organized correctly.
