### ISSUE TITLE
Flipper freezes and must be rebooted when loading UID from file in MIFARE Fuzzer 

### ISSUE THREAD

**Issue by Clats97** [Next-Flip/Momentum-Apps#15]
### Describe the bug.

When selecting a txt file with UIDs in the MIFARE Fuzzer, after pressing attack the flipper zero freezes. 

### Reproduction

1. Turn on flipper
2. Navigate to MIFARE Fuzzer
3. Select card type or from file
4. Select "load UIDs from file"
5. Select the file
6. Press start
7. Flipper Zero freezes.

**Comment by WillyJL** [comment]
working fine here. did you try rebooting? also please try on latest dev build

**Comment by Clats97** [comment]
Yes the reason why it wasn't working was because the keys I generated in Python weren't the right length, so I changed the length to the correct length and it's working, my bad, this issue can be closed and ignored

[signatureImage]
________________________________
