### ISSUE TITLE
[BLE Spam] Increase NameFlood name length limit 

### ISSUE THREAD

**Issue by bns34** [Next-Flip/Momentum-Apps#37]
I've been trying to increase the maximum length of bluetooth names for the NameFlood feature in BLE Spam. I have tried changing `20` to different values in the `nameflood.h` file. Smaller numbers work fine, but numbers larger than 20 seem to cause the Flipper to crash with `furi_check failed`. Is this a limitation with the flipper or am I doing something wrong?

**Comment by WillyJL** [comment]
its a bluetooth limitation. ble advertisements are limited to 31 bytes. there is extra metadata required to indicate that the device is connectable (in order to show in the bluetooth device list) and other info about it. 20 bytes is what is left for the actual name.
