### ISSUE TITLE
More apps?

### ISSUE THREAD

**Issue by ZProLegend007** [Next-Flip/Momentum-Apps#7]
Hey, love the work you guys are doing! Just wondering, if you guys stay up to date with the https://github.com/xMasterX/all-the-plugins repo? It would be great to have all the latest apps on the momentum releases.

**Comment by WillyJL** [comment]
We add the ones we find interesting or useful or cool. Adding all of them though is probably a no, but we are always open to individual app suggestions and requests!

**Comment by ZProLegend007** [comment]
Ah makes sense, thanks for the swift reply! There have been some new apps recently that are quite good, I've just started experimenting with the video player, that could be an awesome addition with some videos added by default. I have some random fun ones from youtube I can upload if you would like. The app works quite better than expected. Otherwise I might have a look at some individual apps later on... Thanks.
